---
stages:
- prepare
- test
- lint
- build
- deploy

yarn:install:
  artifacts:
    paths:
    - node_modules/
  cache:
    paths:
    - node_modules/
  image: docker.input-output.dk/docker/nodejs:7.5.0
  script:
  - yarn install
  stage: prepare
  tags:
  - kubernetes

lint:
  dependencies:
  - yarn:install
  image: docker.input-output.dk/docker/nodejs:7.5.0
  script:
  - yarn lint
  stage: lint
  tags:
  - kubernetes

test:7.5.0:
  dependencies:
  - yarn:install
  image: docker.input-output.dk/docker/nodejs:7.5.0
  script:
  - yarn test
  stage: test
  tags:
  - kubernetes

test:6.9.5:
  dependencies:
  - yarn:install
  image: docker.input-output.dk/docker/nodejs:6.9.5
  script:
  - yarn test
  stage: test
  tags:
  - kubernetes

build:
  artifacts:
    paths:
    - dist/
    - lib/
    - lib2015/
  dependencies:
    - yarn:install
  image: docker.input-output.dk/docker/nodejs:7.5.0
  script:
  - yarn build --production
  stage: build
  tags:
  - kubernetes

publish:
  dependencies:
  - build
  image: docker.input-output.dk/docker/nodejs:7.5.0
  only:
  - tags
  - triggers
  script:
  - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
  - npm publish
  stage: deploy
  tags:
  - kubernetes
  when: manual
