---
stages:
- test
- lint
- build

cache:
  paths:
  - node_modules/

lint:
  image: node:7.5.0-alpine
  stage: lint
  script:
  - npm install
  - npm run lint

test:7.5.0:
  image: node:7.5.0-alpine
  script:
  - npm install
  - npm test
  stage: test

test:6.9.5:
  image: node:6.9.5-alpine
  script:
  - npm install
  - npm test
  stage: test

test:4.7.3:
  image: node:4.7.3-alpine
  script:
  - npm install
  - node --harmony_modules --harmony_array_includes --harmony_regexps --harmony_proxies --harmony_sloppy --harmony_unicode_regexps --harmony_reflect --harmony_destructuring --harmony_sharedarraybuffer --harmony_atomics --harmony_new_target --harmony_tostring --harmony_concat_spreadable --harmony_rest_parameters --harmony_spreadcalls --harmony_spread_arrays --harmony_arrow_functions --harmony_computed_property_names --harmony_unicode --harmony_object ./node_modules/jest-cli/bin/jest
  stage: test

build:
  artifacts:
    paths:
    - dist/
    - lib/
    - lib2015/
  dependencies:
    - lint
    - test:4.7.3
    - test:6.9.5
    - test:7.5.0
  image: node:7.5.0-alpine
  script:
  - npm install
  - npm run build
  stage: build
