---
stages:
- prepare
- test
- lint
- build

npm:install:
  artifacts:
    paths:
    - node_modules/
  cache:
    paths:
    - node_modules/
  image: node:7.5.0-alpine
  script:
  - npm install
  stage: prepare
  tags:
  - kubernetes

lint:
  dependencies:
  - npm:install
  image: node:7.5.0-alpine
  script:
  - npm run lint
  stage: lint
  tags:
  - kubernetes

test:7.5.0:
  dependencies:
  - npm:install
  image: node:7.5.0-alpine
  script:
  - npm test
  stage: test
  tags:
  - kubernetes

test:6.9.5:
  dependencies:
  - npm:install
  image: node:6.9.5-alpine
  script:
  - npm test
  stage: test
  tags:
  - kubernetes

build:
  artifacts:
    paths:
    - dist/
    - lib/
    - lib2015/
  dependencies:
    - npm:install
  image: node:7.5.0-alpine
  script:
  - npm run build
  stage: build
  tags:
  - kubernetes
