---
stages:
- prepare
- lint
- test
- build
- deploy

yarn:install:
  artifacts:
    paths:
    - node_modules/
  cache:
    paths:
    - node_modules/
  image: eu.gcr.io/io-img/nodejs:8.4.0
  script:
  - yarn install
  stage: prepare
  tags:
  - kubernetes

lint:
  dependencies:
  - yarn:install
  image: eu.gcr.io/io-img/nodejs:8.4.0
  script:
  - yarn lint
  stage: lint
  tags:
  - kubernetes

test:8.4.0:
  dependencies:
  - yarn:install
  image: eu.gcr.io/io-img/nodejs:8.4.0
  script:
  - yarn test
  stage: test
  tags:
  - kubernetes

test:7.7.1:
  dependencies:
  - yarn:install
  image: eu.gcr.io/io-img/nodejs:7.7.1
  script:
  - yarn test
  stage: test
  tags:
  - kubernetes

test:6.11.2:
  dependencies:
  - yarn:install
  image: eu.gcr.io/io-img/nodejs:6.11.2
  script:
  - yarn test
  stage: test
  tags:
  - kubernetes

build:
  artifacts:
    paths:
    - dist/
    - lib/
    - lib2015/
    - types/
  dependencies:
    - yarn:install
  image: eu.gcr.io/io-img/nodejs:8.4.0
  script:
  - yarn build --production
  stage: build
  tags:
  - kubernetes

publish:
  dependencies:
  - build
  image: eu.gcr.io/io-img/nodejs:8.4.0
  only:
  - tags
  - triggers
  script:
  - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
  - npm publish
  stage: deploy
  tags:
  - kubernetes
  when: manual
